# Generated by Django 5.2.12 on 2026-05-12 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="questiontag",
            options={
                "verbose_name": "Тег вопроса",
                "verbose_name_plural": "Теги вопросов",
            },
        ),
        migrations.AlterUniqueTogether(
            name="answerlike",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="questionlike",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="answer",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="answerlike",
            name="answer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="questions.answer",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="questionlike",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="questions.question",
            ),
        ),
        migrations.AddConstraint(
            model_name="answerlike",
            constraint=models.UniqueConstraint(
                fields=("answer", "user"), name="unique_answer_like"
            ),
        ),
        migrations.AddConstraint(
            model_name="questionlike",
            constraint=models.UniqueConstraint(
                fields=("question", "user"), name="unique_question_like"
            ),
        ),
    ]
